\set ON_ERROR_STOP on
CREATE OR REPLACE AGGREGATE FUNCTION HllDistinctCount
AS LANGUAGE 'C++'
NAME 'HllDistinctCountFactory'
LIBRARY HllLib FENCED;

GRANT EXECUTE ON AGGREGATE FUNCTION HllDistinctCount(VARBINARY) TO PUBLIC;
